#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes

i=1

while [ $i -le 100 ]
do
       	if [ $((i%15)) = 0 ]
	then 
		echo "FizzBuzz"
	elif [ $(($i%3)) = 0 ]
	then 
		echo "Fizz"
	elif [ $(($i%5)) = 0 ]
	then  echo "Buzz"

	else
		
		echo "$i"
	fi

	((i++))
done
