#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command; sudo rm /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINIT
trap 'sudo rm /var/run/myscript.pid' SIGQUIT
while :
do 
	echo "To infinity and beyond"
	sleep 2
done 

