#!/usr/bin/env bash
#Mananges processes

if [ "${1}" == "start" ]
then ./manage_my_process.pid
	 echo "$$" > /var/run/my_process.pid
	  echo "manage_my_process started"
 
elif [ "${1}" == "stop" ]
then 
	echo "manage_my_process stopped" 
	sudo pkill -f ./manage_my_process
	rm /var/run/my_process.pid
elif [ "${1}" == "restart" ] 
then 
	sudo pkill -f ./manage_my_process
	rm /var/run/my_process.pid 
	echo "$$" > /var/run/my_process.pid 
	echo "manage_my_process restarted"
else 
	echo "Usage: manage_my_process {start|stop|restart}"
fi
